[tools]
bun = "latest"
fzf = "latest"
gh = "latest"
github-cli = "latest"
go = "latest"
jq = "latest"
node = "latest"
python = "latest"
rust = "latest"
starship = "latest"
uv = "latest"
zig = "latest"
zoxide = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]
